### PR TITLE
kevinhermann4 hometown file

### LINKED ISSUE #5: kevinhermann4 - checklist
No issue yet!
 

- [x] Gain professional training in Git and GitHub
- [x]  Create branches
- [x] Learn Git branching strategies. 
- [x] Create a PR request
- [x] Merge

### PR DESCRIPTION
**Pull request by kevinhermann4**
Adding hometown file with some great food recommendations. 

Closes #5

### CODE REVIEW

**Review by stevenhammond — APPROVED** [review]
not sure if those emojis will work. i think it's supposed to be :pizza: - colons on both sides

**Comment by kevinhermann4** [comment]
Fixed!

**Review by stevenhammond — APPROVED** [review]
looks good

**Review by stevenhammond — APPROVED** [review]
looks good

**Comment by kevinhermann4** [comment]
Thanks Steve for your approval!

**Pull request merged**
